best_books/urls.py
from django.contrib import admin
from django.urls import path
from books import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home-page'),
    path('authors/', views.AuthorListView.as_view(), name='authors_list'),
    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='author_detail'),
    path('book/<int:pk>/', views.book_detail, name='book_detail'),
    path('book/<int:book_id>/add-comment/', views.create_book_comment_view, name='add-book-comment'),
    path('contact/', views.ContactView.as_view(), name='contact-view'),
    path('contact-author/<int:pk>/', views.AuthorContactView.as_view(), name='author-contact-view'),
    path('mail-send/', views.MailSendView.as_view(), name='mail-send'),
    path('login/', views.LoginView.as_view(), name='login'),
]

books/models.py
from django.db import models


class Author(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    birth_date = models.DateField(null=True, blank=True)
    bio = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Book(models.Model):
    title = models.CharField(max_length=128)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='books')
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class BookComment(models.Model):
    author = models.CharField(max_length=128)
    content = models.TextField()
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='comments')
    created_at = models.DateTimeField(auto_now_add=True)

books/forms.py
from django import forms
from django.core.mail import send_mail

from books.models import Author


class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)
    terms_of_use = forms.BooleanField(required=True)
    age = forms.IntegerField()

    def send_email(self):
        name = self.cleaned_data.get('name')
        message = self.cleaned_data.get('message')
        send_mail(
            subject=f'Nowy komenatarz do strony od {name}',
            message=message,
            from_email='no-replay@mojastrona.pl',
            recipient_list=['kamilmarekradomski@gmail.com'],
        )


class AuthorContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)
    terms_of_use = forms.BooleanField(required=True)

    def __init__(self, *args, **kwargs):
        self.author_id = kwargs.pop('author_id')
        super().__init__(*args, **kwargs)

    def send_email(self):
        name = self.cleaned_data.get('name')
        message = self.cleaned_data.get('message')
        author = Author.objects.get(pk=self.author_id)
        send_mail(
            subject=f'Nowy komenatarz do strony od {name}',
            message=message,
            from_email='no-replay@mojastrona.pl',
            recipient_list=[f'{author.first_name}_{author.last_name}@bestbooks.pl'],
        )


class LoginForm(forms.Form):
    username = forms.CharField(label='login')
    password = forms.CharField(label='password', widget=forms.PasswordInput)

books/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views.generic import \
    ListView, DetailView, TemplateView, \
    FormView

from books.forms import ContactForm, AuthorContactForm, LoginForm
from books.models import Author, Book, BookComment


class AuthorListView(ListView):
    model = Author
    template_name = 'books/authors_list.html'


class AuthorDetailView(DetailView):
    model = Author
    template_name = 'books/author_detail.html'

    def get_context_data(self, **kwargs):
        context = super(AuthorDetailView, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context


def book_detail(request, pk):
    book = Book.objects.get(pk=pk)
    return render(
        request,
        'books/book_detail.html',
        {'book': book}
    )


class HomePage(TemplateView):
    template_name = 'books/home_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['books'] = Book.objects.all()[:3]
        context['authors'] = Author.objects.all()[:3]
        return context


def create_book_comment_view(request, book_id):
    book = Book.objects.get(pk=book_id)
    if request.method == 'GET':
        return render(
            request,
            'books/book_comment_form.html',
            {'book': book},
        )
    elif request.method == 'POST':
        BookComment.objects.create(
            book=book,
            author=request.POST.get('kto_to_napisal_w_ogole'),
            content=request.POST.get('content'),
        )
        return HttpResponseRedirect(reverse('book_detail', kwargs={'pk': book_id}))


class ContactView(FormView):
    form_class = ContactForm
    template_name = 'books/contact_form.html'
    success_url = reverse_lazy('authors_list')

    def form_valid(self, form):
        form.send_email()
        return super().form_valid(form)


class AuthorContactView(LoginRequiredMixin, FormView):
    form_class = AuthorContactForm
    template_name = 'books/author_contact_form.html'
    success_url = reverse_lazy('mail-send')

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['author'] = Author.objects.get(pk=self.kwargs.get('pk'))
        return ctx

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['author_id'] = self.kwargs.get('pk')
        return kwargs

    def form_valid(self, form):
        form.send_email()
        return super().form_valid(form)


class MailSendView(TemplateView):
    template_name = 'books/mail_send.html'


class LoginView(FormView):
    form_class = LoginForm
    template_name = 'books/login.html'
    success_url = '/'

    def form_valid(self, form):
        user = authenticate(
            self.request,
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password'],
        )
        if user is not None:
            login(self.request, user)
            if self.request.GET.get('next'):
                return HttpResponseRedirect(self.request.GET.get('next'))
            return HttpResponseRedirect('/')
        else:
            return HttpResponseRedirect(f"{reverse('login')}?next={self.request.GET.get('next')}")


class RegisterView(FormView):
    form_class = ...
    template_name = ...
    success_url = ...

    def form_valid(self, form):
        ...

templates/books/author_contact_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Formularz kontaktowy</title>
</head>
<body>
    <h1>Formularz kontaktowy do autora {{ author }}</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Wyślij!">
    </form>
</body>
</html>

templates/books/author_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ author.first_name }} {{ author.last_name }}</title>
</head>
<body>
<h1>{{ author.first_name }} {{ author.last_name }}</h1>
<h3>{{ now }}</h3>
<div>{{ author.bio }}</div>
<h3>Książki:</h3>
{% for book in author.books.all %}
    {{ book.title }}
{% endfor %}
</body>
</html>

templates/books/authors_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lista autorów i autorek</title>
</head>
<body>

{% for author in author_list %}
    <div>
        <a href="{% url 'author_detail' author.id %}">
            {{ author.first_name }} {{ author.last_name }}
        </a>
    </div>
{% endfor %}

</body>
</html>

templates/books/book_comment_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dodaj komentarz do {{ book.title }}</title>
</head>
<body>
<h1>Skomentuj {{ book.title }}</h1>
<form method="post" action="{% url 'add-book-comment' book.id %}">
    {% csrf_token %}
    <label>Autor:
        <input type="text" name="kto_to_napisal_w_ogole">
    </label>
    <label>Komentarz:
        <input type="text" name="content">
    </label>
    <input type="submit" value="Skomentuj">
</form>

</body>
</html>

templates/books/book_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ book.title }} ({{ book.author }})</title>
</head>
<body>

<h1>{{ book.title }} ({{ book.author }})</h1>
<div>
    {{ book.description }}
</div>
<hr>
{% for comment in book.comments.all %}
    <div>
        {{ comment.content }}
        <h4>
            ~ {{ comment.author }}
        </h4>
    </div>
{% endfor %}

<a href="{% url 'add-book-comment' book.pk %}">Dodaj komentarz</a>


</body>
</html>

templates/books/book_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dodaj książkę</title>
</head>
<body>
    <h1>Dodaj książkę</h1>
    <div>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="dodaj">
        </form>
    </div>
</body>
</html>

templates/books/contact_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Formularz kontaktowy</title>
</head>
<body>
    <h1>Formularz kontaktowy</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Wyślij!">
    </form>
</body>
</html>

templates/books/home_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Strona główna</title>
</head>
<body>
<h1>Best Books!</h1>
<div>
    {% for book in books %}
        <a href="{% url 'book_detail' book.pk %}">{{ book.title }}</a>
    {% endfor %}
</div>
<div>
    {% for author in authors %}
        <a href="{% url 'author_detail' author.pk %}">{{ author }}</a>
    {% endfor %}
</div>
</body>
</html>

templates/books/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    <h1>Zaloguj się</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Zaloguj">
    </form>
</body>
</html>

templates/books/mail_send.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Mail został wysałny</h1>
</body>
</html>